name: Checksum

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link to .deb file to get Checksum of'
        required: true
        default: ''
      extension:
        description: 'File Extension to get Checksum of'
        required: true
        default: '.deb'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch file
        run: curl -OL ${{ github.event.inputs.link }}
        
      - name: SHA-1 checksum
        run: sha1sum *${{ github.event.inputs.extension }}
        
      - name: MD5 checksum
        run: md5sum *${{ github.event.inputs.extension }}
        
      - name: SHA-256 checksum
        run: sha256sum *${{ github.event.inputs.extension }}
